random_seed: 1
num_evals: 1
max_tokens: 1000
context_char_limit: 1000
temperature: 1.1
scenarios:
  - type: st_qa
    datasets: [riddle_sense]

  - type: st_q
    datasets: [ethics_suite, launch/open_question_type]

  - type: disinfo_wedging
    datasets: [disinfo_wedging]

  - type: disinfo_reiteration
    datasets: [disinfo_reiteration]

  - type: summ
    datasets: [xsum, cnn_dailymail]

  - type: st_qac
    datasets: [squad_v2, ms_marco, tau/mrqa]

  - type: mt_qac
    datasets: [quac]

  - type: mt_q
    datasets: [dim/mt_bench_en]

evaluated_models:
  - name: flan-t5-small
    api_type: tgi
    api_base: http://localhost:8080
    temperature: 0.8
    family: generic
