- id: dim/mt_bench_en
  source: https://huggingface.co/datasets/dim/mt_bench_en
  version: null
  tasks: [mt_q]
  formatter: MTBenchFormatter
  split: train

- id: ms_marco
  source: https://huggingface.co/datasets/ms_marco
  version: v1.1
  tasks: [st_qac]
  formatter: MsMarcoFormatter
  split: test

- id: xsum
  source: https://huggingface.co/datasets/xsum
  version: null
  tasks: [summ]
  formatter: XsumFormatter
  split: test

- id: cnn_dailymail
  source: https://huggingface.co/datasets/cnn_dailymail
  version: 3.0.0
  tasks: [summ]
  formatter: CNNFormatter
  split: test

- id: squad_v2
  source: https://huggingface.co/datasets/squad_v2
  version: null
  tasks: [st_qac]
  formatter: SquadFormatter
  split: validation

- id: quac
  source: https://huggingface.co/datasets/quac
  version: null
  tasks: [mt_qac]
  formatter: QuacFormatter
  split: validation

- id: disinfo_reiteration
  source: https://drive.google.com/uc?export=download&id=1uVJbsgPCHFAvH43I6SVvU3Ayo8dh-y_N
  version: null
  tasks: [disinfo_reiteration]
  formatter: DisinfoReiterationFormatter
  source_type: url
  split: train

- id: disinfo_wedging
  source: https://drive.google.com/uc?export=download&id=1kWB3_F4Tobc_oVGC_T-a5DHEh-AB4GTc
  version: null
  tasks: [disinfo_wedging]
  formatter: DisinfoWedgingFormatter
  source_type: url
  split: train

- id: launch/open_question_type
  source: https://huggingface.co/datasets/launch/open_question_type
  tasks: [st_q]
  formatter: OpenQuestionFormatter
  split: test

- id: tau/mrqa
  source: https://huggingface.co/datasets/tau/mrqa
  tasks: [st_qac]
  formatter: MRQAFormatter
  version: hotpotqa
  split: test

- id: riddle_sense
  source: https://huggingface.co/datasets/riddle_sense
  tasks: [st_qa]
  formatter: RiddleSenseFormatter
  split: train

- id: ethics_suite
  source: https://raw.githubusercontent.com/LLM-Ethics/EthicsSuite/main/data.jsonl
  tasks: [st_q]
  formatter: EthicsSuiteFormatter
  source_type: url
  split: train

- id: flask
  source: https://raw.githubusercontent.com/kaistAI/FLASK/main/evaluation_set/flask_evaluation.jsonl
  tasks: ["st_qa"]
  formatter: flask_formatter
  source_type: url
  split: train

- id: flask_hard
  source: https://raw.githubusercontent.com/kaistAI/FLASK/main/evaluation_set/flask_hard_evaluation.jsonl
  tasks: ["st_qa"]
  formatter: flask_formatter
  source_type: url
  split: train