judge: gpt-3.5-turbo
judge_api_key: null
judge_temperature: 0.2
use_proxy: false
proxies:
  http: http://sample-proxy
  https: http://sample-proxy
random_seed: 54536
num_evals: 2
max_tokens: 1000
context_char_limit: 1000
temperature: 1.1
scenarios: ["qa", "dis_w"]
models:
  - id: flan-t5-small
    api_type: tgi
    api_base: http://localhost:8080
    temperature: 1.5
    family: generic
