num_evals: 2
max_tokens: 1000
context_char_limit: 1000
temperature: 1.1
scenarios: ["qa", "dis_w"]
random_seed: 54536
judge:
  name: gpt-3.5-turbo
  api_type: openai
  api_key: null
  temperature: 0.2
  use_proxy: false
  proxies:
    http: http://sample-proxy
    https: http://sample-proxy
models:
  - id: flan-t5-small
    api_type: tgi
    api_base: http://localhost:8080
    api_key: null
    temperature: 1.5
    family: generic
  - id: gpt-3.5-turbo
    api_type: openai
    api_key: null
    temperature: 1.5
    family: generic
