- id: dim/mt_bench_en
  source: https://huggingface.co/datasets/dim/mt_bench_en
  version: null
  tasks:
    - id: mt_q
      formatter: MTBenchFormatter
  source_type: hub
  split: train
  tags: ["instruction_following", "open_ended"]

- id: ms_marco
  source: https://huggingface.co/datasets/ms_marco
  version: v1.1
  tasks:
    - id: st_qac
      formatter: MsMarcoFormatter
  source_type: hub
  split: test
  tags: ["summarization", "documents", "info_retrieval"]

- id: xsum
  source: https://huggingface.co/datasets/xsum
  version: null
  tasks:
    - id: summ
      formatter: XsumFormatter
  source_type: hub
  split: test
  tags: ["summarization", "documents"]

- id: cnn_dailymail
  source: https://huggingface.co/datasets/cnn_dailymail
  version: 3.0.0
  tasks:
    - id: summ
      formatter: CNNFormatter
  source_type: hub
  split: test
  tags: ["summarization", "documents"]

- id: squad_v2
  source: https://huggingface.co/datasets/squad_v2
  version: null
  tasks:
    - id: st_qac
      formatter: SquadFormatter
  source_type: hub
  split: validation
  tags: ["question_answering"]

- id: quac
  source: https://huggingface.co/datasets/quac
  version: null
  tasks:
    - id: mt_qac
      formatter: QuacFormatter
  source_type: hub
  split: validation
  tags: ["question_answering"]

- id: disinfo_reiteration
  source: https://drive.google.com/uc?export=download&id=1uVJbsgPCHFAvH43I6SVvU3Ayo8dh-y_N
  version: null
  tasks:
    - id: disinfo_reiteration
      formatter: DisinfoReiterationFormatter
  source_type: url
  split: train
  tags: ["harms", "disinformation"]

- id: disinfo_wedging
  source: https://drive.google.com/uc?export=download&id=1kWB3_F4Tobc_oVGC_T-a5DHEh-AB4GTc
  version: null
  tasks:
    - id: disinfo_wedging
      formatter: DisinfoWedgingFormatter
  source_type: url
  split: train
  tags: ["harms", "disinformation"]

- id: launch/open_question_type
  source: https://huggingface.co/datasets/launch/open_question_type
  tasks:
    - id: st_q
      formatter: OpenQuestionFormatter
  source_type: hub
  split: test
  tags: ["question_answering", "open_ended", "reasoning", "commonsense"]

- id: riddle_sense
  source: https://huggingface.co/datasets/riddle_sense
  tasks:
    - id: st_qa
      formatter: RiddleSenseFormatter
  source_type: hub
  split: train
  tags: ["question_answering", "reasoning", "commonsense"]

- id: ethics_suite
  source: https://raw.githubusercontent.com/LLM-Ethics/EthicsSuite/main/data.jsonl
  tasks:
    - id: st_q
      formatter: EthicsSuiteFormatter
  source_type: url
  split: train
  tags: ["open_ended", "harms", "question_answering",]

- id: gsm8k
  source: https://huggingface.co/datasets/gsm8k
  version: main
  tasks:
    - id: st_qa
      formatter: GSM8KFormatter
    - id: st_q
      formatter: GSM8KFormatterSTQ
  source_type: hub
  split: test
  tags: ["maths"]

- id: flask
  source: https://raw.githubusercontent.com/kaistAI/FLASK/main/evaluation_set/flask_evaluation.jsonl
  tasks:
    - id: st_qam
      formatter: FlaskFormatter
  source_type: url
  split: train
  split: test
  tags: ["instruction_following"]

- id: flask_hard
  source: https://raw.githubusercontent.com/kaistAI/FLASK/main/evaluation_set/flask_hard_evaluation.jsonl
  tasks:
    - id: st_qam
      formatter: FlaskFormatter
  source_type: url
  split: train
  split: test
  tags: ["instruction_following"]
